service: sns-webpush-angular-universal

plugins:
  - serverless-apigw-binary

custom:
  apigwBinary:
    types:
      - '*/*'

provider:
  name: aws
  runtime: java8
  memorySize: 384
  timeout: 300
  stage: production
  region: eu-central-1
  environment:
    TABLE_NAME: ${self:service}
    VAPID_PRIVATE_KEY: ${env:VAPID_PRIVATE_KEY}
    VAPID_PUBLIC_KEY: ${env:VAPID_PUBLIC_KEY}
    SAFARI_KEY_PASSWORD: ${env:SAFARI_KEY_PASSWORD}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:service}_vapidSubscriptions"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:service}_safariSubscriptions"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:service}_logs"

package:
  artifact: target/aws-sns-webpush-1.0-SNAPSHOT.jar
  exclude:
    - ./**
  include:
    - target/aws-sns-webpush-1.0-SNAPSHOT.jar

functions:
  api:
    handler: com.maciejtreder.aws.webpush.handlers.HttpHandler::handleRequest
    events:
      - http: ANY {proxy+}
      - http: ANY /

  sns:
    handler: com.maciejtreder.aws.webpush.handlers.SnsHandler::handleRequest
    events:
      - sns: ${self:service}


resources:
  Resources:
    vapidSubscirptionsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: subscription
            AttributeType: S
        KeySchema:
          -
            AttributeName: subscription
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: '${self:service}_vapidSubscriptions'
    safariSubscriptionsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: websitePushId
            AttributeType: S
          -
            AttributeName: deviceToken
            AttributeType: S
        KeySchema:
          -
            AttributeName: websitePushId
            KeyType: HASH
          -
            AttributeName: deviceToken
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: '${self:service}_safariSubscriptions'
    logsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: timestamp
            AttributeType: S
        KeySchema:
          -
            AttributeName: timestamp
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: '${self:service}_logs'